import pg from 'pg';

const mapBooking = r => r && ({ id:r.id, therapistId:r.therapist_id, clientId:r.client_id, startTime:r.start_time.toISOString(), endTime:r.end_time.toISOString(), status:r.status, calendarEventId:r.calendar_event_id, createdAt:r.created_at.toISOString() });
const mapClient = r => r && ({ id:r.id, therapistId:r.therapist_id, name:r.name, phone:r.phone });
export class PostgresStore {
  constructor(url) { this.pool = new pg.Pool({ connectionString: url, ssl: process.env.PGSSL === 'true' ? { rejectUnauthorized: false } : undefined }); }
  async dashboard() { const therapist = (await this.pool.query('SELECT id, name, timezone, session_minutes, fee_paise, google_refresh_token, google_calendar_id FROM therapists ORDER BY created_at LIMIT 1')).rows[0]; if (!therapist) throw new Error('No therapist exists. Seed or onboard a therapist first.'); const [clients, bookings, payments, escalations] = await Promise.all([this.pool.query('SELECT id, therapist_id, name, phone FROM clients'), this.pool.query('SELECT * FROM bookings ORDER BY start_time'), this.pool.query('SELECT * FROM payments ORDER BY created_at DESC'), this.pool.query('SELECT c.* FROM conversations c WHERE escalated = true')]); return { therapist: { id: therapist.id, name: therapist.name, timezone: therapist.timezone, sessionMinutes: therapist.session_minutes, fee: therapist.fee_paise / 100, googleRefreshToken: therapist.google_refresh_token, googleCalendarId: therapist.google_calendar_id }, clients: clients.rows.map(mapClient), bookings: bookings.rows.map(mapBooking), payments: payments.rows.map(p => ({ id:p.id, bookingId:p.booking_id, amount:p.amount_paise / 100, status:p.status, link:p.payment_link })), escalations: await Promise.all(escalations.rows.map(r => this.conversation(r.client_id))) }; }
  async client(id) { return mapClient((await this.pool.query('SELECT id, therapist_id, name, phone FROM clients WHERE id=$1',[id])).rows[0]); }
  async clientByPhone(phone) { return mapClient((await this.pool.query('SELECT id, therapist_id, name, phone FROM clients WHERE phone=$1 LIMIT 1',[phone])).rows[0]); }
  async ensureClient(phone) { let c = await this.clientByPhone(phone); if (c) return c; const therapist = (await this.pool.query('SELECT id FROM therapists ORDER BY created_at LIMIT 1')).rows[0]; if (!therapist) throw new Error('No therapist is configured.'); const row = (await this.pool.query('INSERT INTO clients (therapist_id,name,phone) VALUES ($1,$2,$3) RETURNING id,therapist_id,name,phone',[therapist.id,'WhatsApp Client',phone])).rows[0]; return mapClient(row); }
  async conversation(clientId) { await this.pool.query('INSERT INTO conversations (client_id) VALUES ($1) ON CONFLICT (client_id) DO NOTHING',[clientId]); const c = (await this.pool.query('SELECT * FROM conversations WHERE client_id=$1',[clientId])).rows[0]; const messages = await this.pool.query('SELECT id,role,content,created_at FROM messages WHERE client_id=$1 ORDER BY created_at',[clientId]); return { clientId, state:c.state, pendingDate:c.pending_date?.toISOString().slice(0,10) || null, escalated:c.escalated, updatedAt:c.updated_at.toISOString(), messages:messages.rows.map(m=>({id:m.id,role:m.role,content:m.content,timestamp:m.created_at.toISOString()})) }; }
  async message(clientId,role,content) { await this.conversation(clientId); await this.pool.query('INSERT INTO messages (client_id,role,content) VALUES ($1,$2,$3)',[clientId,role,content]); await this.pool.query('UPDATE conversations SET updated_at=now() WHERE client_id=$1',[clientId]); return this.conversation(clientId); }
  async setConversation(clientId, changes) { await this.conversation(clientId); await this.pool.query('UPDATE conversations SET state=COALESCE($2,state), pending_date=$3, escalated=COALESCE($4,escalated), updated_at=now() WHERE client_id=$1',[clientId,changes.state ?? null,changes.pendingDate ?? null,changes.escalated ?? null]); }
  async bookings(clientId) { return (await this.pool.query(`SELECT * FROM bookings ${clientId ? 'WHERE client_id=$1' : ''} ORDER BY start_time`,clientId?[clientId]:[])).rows.map(mapBooking); }
  async booking(id) { return mapBooking((await this.pool.query('SELECT * FROM bookings WHERE id=$1',[id])).rows[0]); }
  async createBooking(v) { return mapBooking((await this.pool.query('INSERT INTO bookings (therapist_id,client_id,start_time,end_time,status,calendar_event_id) VALUES ($1,$2,$3,$4,$5,$6) RETURNING *',[v.therapistId,v.clientId,v.startTime,v.endTime,v.status || 'confirmed',v.calendarEventId || null])).rows[0]); }
  async updateBooking(id,v) { return mapBooking((await this.pool.query('UPDATE bookings SET start_time=COALESCE($2,start_time), end_time=COALESCE($3,end_time), status=COALESCE($4,status), calendar_event_id=COALESCE($5,calendar_event_id) WHERE id=$1 RETURNING *',[id,v.startTime ?? null,v.endTime ?? null,v.status ?? null,v.calendarEventId ?? null])).rows[0]); }
  async createPayment(v) { const row=(await this.pool.query('INSERT INTO payments (booking_id,amount_paise,status,payment_link) VALUES ($1,$2,$3,$4) RETURNING *',[v.bookingId,Math.round(v.amount*100),v.status || 'pending',v.link || null])).rows[0]; return { id:row.id,bookingId:row.booking_id,amount:row.amount_paise/100,status:row.status,link:row.payment_link }; }
  async updatePaymentByProvider(id,changes) { const r=(await this.pool.query('UPDATE payments SET status=$2 WHERE provider_payment_id=$1 RETURNING *',[id,changes.status])).rows[0]; return r && {id:r.id,bookingId:r.booking_id,amount:r.amount_paise/100,status:r.status}; }
  async saveGoogleTokens(therapistId,tokens) { await this.pool.query('UPDATE therapists SET google_refresh_token=COALESCE($2,google_refresh_token) WHERE id=$1',[therapistId,tokens.refresh_token ?? null]); }
  async googleConnection(therapistId) { const r=(await this.pool.query('SELECT google_refresh_token,google_calendar_id FROM therapists WHERE id=$1',[therapistId])).rows[0]; return r && { refreshToken:r.google_refresh_token, calendarId:r.google_calendar_id || 'primary' }; }
  async claimWebhookEvent(provider,eventId) { const result=await this.pool.query('INSERT INTO webhook_events (provider,event_id) VALUES ($1,$2) ON CONFLICT DO NOTHING',[provider,eventId]); return result.rowCount === 1; }
  async conversations() { const rows=await this.pool.query('SELECT client_id FROM conversations ORDER BY updated_at DESC'); return Promise.all(rows.rows.map(r=>this.conversation(r.client_id))); }
  async close() { await this.pool.end(); }
}
export async function createStore() { return process.env.DATABASE_URL ? new PostgresStore(process.env.DATABASE_URL) : (await import('./store.js')).store; }
